# Configure Markup <https://gohugo.io/getting-started/configuration-markup#configure-markup>

# Goldmark is from Hugo 0.60 the default library used for Markdown
goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    # This extension substitutes punctuations with typographic entities like smartypants
    typographer: true
  parser:
    attribute: true
    autoHeadingID: true
    # The strategy used for creating auto IDs (anchor names)
    autoHeadingIDType: 'github'
  renderer:
    hardWraps: false
    # By default, Goldmark does not render raw HTMLs and potentially dangerous links. If you have lots of
    # inline HTML and/or JavaScript, you may need to turn this on
    unsafe: false
    xhtml: false
